@isTest
public class classTest {   // Test Class
// @isTest
static void methodTest() {   // test class method 1
        
         Account c = new Account(name ='abc');  // inserting name in account
         insert c;
        
         ApexPages.StandardController sc = new ApexPages.standardController(c);   // constructor of standard controller
         ManipulateContactExtension obj = new ManipulateContactExtension(sc);           

        
   
   
          
 
    }
}